import traceback
from ansible.utils import safe_eval

def test_safe_eval():
    exploit_code = "__import__('os').system('echo Exploit Successful')"
    try:
        # Attempt to execute the exploit code using safe_eval
        safe_eval.safe_eval(exploit_code)
        print('The ACI unit test is failed!!!')
    except Exception:
        # If an exception occurs, it means the exploit was not successful
        print('The ACI unit test is passed!!!')

if __name__ == "__main__":
    test_safe_eval()
