
            Now there is a CVE in this repo:The password hasher in contrib/auth/hashers.py in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to enumerate users via a timing attack involving login requests..
            Now the following functions is the cause for the CVE:tests/auth_tests/test_hashers.py:test_bcrypt_harden_runtime();tests/auth_tests/test_hashers.py:test_check_password_calls_harden_runtime();tests/auth_tests/test_hashers.py:test_pbkdf2_harden_runtime();django/contrib/auth/hashers.py:check_password();django/contrib/auth/hashers.py:check_password();django/contrib/auth/hashers.py:harden_runtime();django/contrib/auth/hashers.py:verify();django/contrib/auth/hashers.py:verify();
            