
            Now there is a CVE in this repo:(1) core/tests/test_memmap.py, (2) core/tests/test_multiarray.py, (3) f2py/f2py2e.py, and (4) lib/tests/test_io.py in NumPy before 1.8.1 allow local users to write to arbitrary files via a symlink attack on a temporary file..
            Now the following functions is the cause for the CVE:numpy/lib/tests/test_io.py:tempdir();numpy/lib/tests/test_io.py:test_big_arrays();numpy/lib/tests/test_io.py:test_big_arrays();numpy/core/tests/test_multiarray.py:setUp();numpy/core/tests/test_multiarray.py:setUp();numpy/core/tests/test_multiarray.py:tearDown();numpy/core/tests/test_multiarray.py:tearDown();numpy/core/tests/test_multiarray.py:test_file_position_after_fromfile();numpy/core/tests/test_multiarray.py:test_file_position_after_tofile();numpy/core/tests/test_multiarray.py:test_roundtrip_file();numpy/core/tests/test_multiarray.py:test_tofile_sep();numpy/core/tests/test_memmap.py:test_filename();numpy/core/tests/test_memmap.py:test_filename();numpy/core/tests/test_memmap.py:test_open_with_filename();numpy/core/tests/test_memmap.py:test_open_with_filename();numpy/f2py/f2py2e.py:run_compile();numpy/f2py/f2py2e.py:run_compile();
            