
            Now there is a CVE in this repo:The utils.http.is_safe_url function in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by http://mysite.example.com\\@attacker.com..
            Now the following functions is the cause for the CVE:django/utils/http.py:_is_safe_url();django/utils/http.py:is_safe_url();django/utils/http.py:is_safe_url();tests/utils_tests/test_http.py:test_is_safe_url();
            