
            Now there is a CVE in this repo:The chroot, jail, and zone connection plugins in ansible before 1.9.2 allow local users to escape a restricted environment via a symlink attack..
            Now the following functions is the cause for the CVE:lib/ansible/plugins/connections/chroot.py:_buffered_exec_command();lib/ansible/plugins/connections/chroot.py:_generate_cmd();lib/ansible/plugins/connections/chroot.py:exec_command();lib/ansible/plugins/connections/chroot.py:exec_command();lib/ansible/plugins/connections/chroot.py:fetch_file();lib/ansible/plugins/connections/chroot.py:fetch_file();lib/ansible/plugins/connections/chroot.py:put_file();lib/ansible/plugins/connections/chroot.py:put_file();lib/ansible/plugins/connections/zone.py:_buffered_exec_command();lib/ansible/plugins/connections/zone.py:_copy_file();lib/ansible/plugins/connections/zone.py:_generate_cmd();lib/ansible/plugins/connections/zone.py:_normalize_path();lib/ansible/plugins/connections/zone.py:exec_command();lib/ansible/plugins/connections/zone.py:exec_command();lib/ansible/plugins/connections/zone.py:fetch_file();lib/ansible/plugins/connections/zone.py:fetch_file();lib/ansible/plugins/connections/zone.py:list_zones();lib/ansible/plugins/connections/zone.py:list_zones();lib/ansible/plugins/connections/zone.py:put_file();lib/ansible/plugins/connections/zone.py:put_file();lib/ansible/plugins/connections/jail.py:_buffered_exec_command();lib/ansible/plugins/connections/jail.py:_copy_file();lib/ansible/plugins/connections/jail.py:_normalize_path();lib/ansible/plugins/connections/jail.py:connect();lib/ansible/plugins/connections/jail.py:connect();lib/ansible/plugins/connections/jail.py:exec_command();lib/ansible/plugins/connections/jail.py:exec_command();lib/ansible/plugins/connections/jail.py:fetch_file();lib/ansible/plugins/connections/jail.py:fetch_file();lib/ansible/plugins/connections/jail.py:put_file();lib/ansible/plugins/connections/jail.py:put_file();
            